FROM php:8.2-apache

RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN a2enmod rewrite

RUN echo '<Directory /var/www/html>\n\
    Options Indexes FollowSymLinks\n\
    AllowOverride All\n\
    Require all granted\n\
</Directory>' > /etc/apache2/conf-available/site.conf \
 && a2enconf site

WORKDIR /var/www/html
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader

RUN a2enmod ssl proxy proxy_http proxy_wstunnel
RUN echo '<VirtualHost *:443>\n\
    DocumentRoot /var/www/html\n\
    SSLEngine on\n\
    SSLCertificateFile /etc/ssl/certs/server.crt\n\
    SSLCertificateKeyFile /etc/ssl/private/server.key\n\
    <Directory /var/www/html>\n\
        Options Indexes FollowSymLinks\n\
        AllowOverride All\n\
        Require all granted\n\
    </Directory>\n\
    ProxyPreserveHost On\n\
    ProxyPass /api/ http://api:8000/\n\
    ProxyPassReverse /api/ http://api:8000/\n\
    ProxyPass /admin-api/ http://admin-api:8001/\n\
    ProxyPassReverse /admin-api/ http://admin-api:8001/\n\
</VirtualHost>' > /etc/apache2/sites-available/default-ssl.conf \
 && a2ensite default-ssl
EXPOSE 443
EXPOSE 80